{
	"version": 1743818057,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/logo-sheet0.png",
		"images/background-default-000.jpg",
		"images/background2-default-000.jpg",
		"images/background3-default-000.jpg",
		"images/background4-default-000.jpg",
		"images/explosion1-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/playerlaser-sheet0.png",
		"images/gunflare-sheet0.png",
		"images/enemyspawner-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/enemybullet-sheet1.png",
		"images/bladeenemy-sheet0.png",
		"images/bladeenemy-sheet1.png",
		"images/explosion2-sheet0.png",
		"images/explosion3-sheet0.png",
		"images/explosion3-sheet1.png",
		"images/explosion3-sheet2.png",
		"images/healthbar.png",
		"images/healthbg.png",
		"images/spikeyenemy-sheet0.png",
		"images/spikeyenemy-sheet1.png",
		"images/playerrocket-sheet0.png",
		"images/rocketpowerup-sheet0.png",
		"images/rocketsdisplay.png",
		"images/playerthrust-sheet0.png",
		"images/bugenemy-sheet0.png",
		"images/bugenemy-sheet1.png",
		"images/enemylaser-sheet0.png",
		"images/fighterenemy-sheet0.png",
		"images/rocketbutton-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite13-sheet1.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/intro-sheet0.png",
		"media/lazer fire 1.m4a",
		"media/lazer fire 1.ogg",
		"media/explosion 1.m4a",
		"media/explosion 1.ogg",
		"media/retrolaser1.m4a",
		"media/retrolaser1.ogg",
		"media/lazer ricochet.m4a",
		"media/lazer ricochet.ogg",
		"media/explosion 4.m4a",
		"media/explosion 4.ogg",
		"media/squaremotif1.m4a",
		"media/squaremotif1.ogg",
		"media/upgrade1.m4a",
		"media/upgrade1.ogg",
		"media/tronblast1.m4a",
		"media/tronblast1.ogg",
		"media/jetloop1.m4a",
		"media/jetloop1.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/explosion 2.m4a",
		"media/explosion 2.ogg",
		"media/retrolaser2.m4a",
		"media/retrolaser2.ogg",
		"media/orbital-colossus.ogg",
		"media/epicarpg.m4a",
		"media/epicarpg.ogg",
		"media/mattoglseby - 3.m4a",
		"media/mattoglseby - 3.ogg",
		"media/backsound.ogg",
		"media/game over ii.ogg",
		"media/deathmatch (boss theme).ogg",
		"media/n-dimensions-_main-theme_.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}